export const matrixAppearance = {
  variables: {
    colorPrimary: "#00ff41",
    colorBackground: "#000000",
    colorText: "#00ff41",
    colorTextSecondary: "#00cc33",
    colorTextOnPrimaryBackground: "#000000",
    colorInputBackground: "#000000",
    colorInputText: "#00ff41",
    colorNeutral: "#003300",
    colorDanger: "#ff4141",
    colorSuccess: "#00ff41",
    colorWarning: "#ffaa00",
    borderRadius: "0px",
    fontFamily: '"Courier New", monospace',
    fontFamilyButtons: '"Courier New", monospace',
    fontSize: "13px",
    spacingUnit: "16px",
  },
  elements: {
    rootBox: { width: "100%" },
    card: {
      background: "#000",
      border: "1px solid #00ff41",
      boxShadow: "0 0 60px rgba(0,255,65,0.12), 0 0 20px rgba(0,255,65,0.06)",
      padding: "36px",
      width: "100%",
      maxWidth: "420px",
      borderRadius: "0",
    },
    headerTitle: {
      color: "#00ff41",
      fontSize: "15px",
      letterSpacing: "0.18em",
      textTransform: "uppercase",
      textShadow: "0 0 12px rgba(0,255,65,0.5)",
      fontWeight: "700",
    },
    headerSubtitle: {
      color: "#004400",
      fontSize: "11px",
      letterSpacing: "0.06em",
    },
    // Social buttons
    socialButtonsBlockButton: {
      background: "#000",
      border: "1px solid #1a3a1a",
      color: "#00cc33",
      letterSpacing: "0.1em",
      borderRadius: "0",
      transition: "border-color 0.15s, background 0.15s",
    },
    socialButtonsBlockButtonText: {
      color: "#00cc33",
      letterSpacing: "0.1em",
      textTransform: "uppercase",
      fontSize: "12px",
    },
    // Grayscale the Google/GitHub colour icons so they don't clash
    socialButtonsProviderIcon: {
      filter: "grayscale(1) brightness(1.5)",
      opacity: "0.6",
    },
    dividerLine: { background: "#0d1f0d" },
    dividerText: {
      color: "#003300",
      letterSpacing: "0.12em",
      textTransform: "uppercase",
      fontSize: "10px",
    },
    formFieldLabel: {
      color: "#004d00",
      letterSpacing: "0.14em",
      textTransform: "uppercase",
      fontSize: "10px",
    },
    formFieldInput: {
      background: "#000",
      border: "1px solid #1a3a1a",
      color: "#00ff41",
      borderRadius: "0",
      fontFamily: '"Courier New", monospace',
    },
    formFieldInputShowPasswordButton: { color: "#004400" },
    formButtonPrimary: {
      background: "#000",
      border: "1px solid #00ff41",
      color: "#00ff41",
      letterSpacing: "0.18em",
      textTransform: "uppercase",
      textShadow: "0 0 8px rgba(0,255,65,0.4)",
      boxShadow: "0 0 16px rgba(0,255,65,0.08)",
      borderRadius: "0",
      fontFamily: '"Courier New", monospace',
    },
    formButtonReset: {
      color: "#004400",
      letterSpacing: "0.08em",
    },
    footerActionText: { color: "#003300", fontSize: "11px", letterSpacing: "0.04em" },
    footerActionLink: { color: "#00cc33", letterSpacing: "0.04em" },
    // Hide "Secured by Clerk" branding + development mode badge
    footer: { display: "none" },
    // OTP / verification code inputs
    otpCodeFieldInput: {
      background: "#000",
      border: "1px solid #1a3a1a",
      color: "#00ff41",
      borderRadius: "0",
    },
    identityPreviewText: { color: "#00cc33" },
    identityPreviewEditButton: { color: "#004400" },
    alertText: { color: "#ff4141", fontSize: "11px" },
    formFieldErrorText: { color: "#ff4141", fontSize: "11px" },
    badge: { display: "none" }, // development mode badge
    // Navbar / profile
    profileSectionTitleText: { color: "#00cc33", letterSpacing: "0.1em" },
    userPreviewMainIdentifier: { color: "#00ff41" },
    userPreviewSecondaryIdentifier: { color: "#004400" },
  },
};
